openapi: 3.0.3
info:
  title: API сервер для личного проекта «Что посмотреть».
  description: |-
    * Список ресурсов и маршрутов сервера «Что посмотреть».
  version: 1.0.0
tags:
  - name: users
    description: Действия с пользователем.
  - name: films
    description: Действия с фильмами.
  - name: comments
    description: Действия с комментариями.

paths:
  /users/register:
    post:
      tags:
        - users
      summary: Создание нового пользователя
      description: Регистрирует нового пользователя.

      requestBody:
        description: Информация для создания нового пользователя.
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/createUser'

      responses:
        "201":
          description: Возвращает созданного пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
                
        "400":
          description: Неверный формат запроса.

        "409":
          description: Пользователь с таким email уже существует.

  /users/login:
    post:
      tags:
        - users
      summary: Вход в закрытую часть приложения
      description: Авторизует пользователя на основе логина и пароля.

      requestBody:
        required: true
        description: Логин и пароль авторизующегося пользователя.
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  example: test@mail.ru
                password:
                  type: string
                  example: 123456

      responses:
        "200":
          description: >
            Успешно авторизован. Возвращается JWT Bearer токен для дальнейшего взаимодействия с API.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    format: jwt

        "401":
          description: Неверный логин или пароль.

    get:
      tags:
        - users
      summary: Проверка состояния пользователя
      description: Возвращает информацию по авторизованному пользователю.
      parameters:
        - in: cookie
          name: Authorization
          required: true
          schema:
            type: string
            format: Bearer jwt

      responses:
        "200":
          description: Информация о пользователе.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "401":
          description: Пользователь не авторизован.

  /films/create:
    post:
      tags:
        - films
      summary: Добавление нового фильма
      description: Добавляет новый фильм.

      requestBody:
        description: Информация для добавления нового фильма.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/film'
        required: true

      responses:
        "201":
          description: Фильм добавлен. Объект фильма.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/film'

        "400":
          description: Неверный формат запроса.

        "401":
          description: Пользователь не авторизован.

  /films/{filmId}:
    get:
      tags:
        - films
      summary: Получение детальной информации по фильму
      description: Получает детальную информацию по определенному фильму.

      parameters:
        - in: path
          name: filmId
          schema:
            type: string
            format: uuid
          required: true
          description: Идентификатор фильма.

      responses:
        "200":
          description: Успешно. Детальная информация по фильму.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/film'

        "404":
          description: Фильма с данным id не существует.

    patch:
      tags:
        - films
      summary: Редактирование карточки фильма
      description: Редактирует карточку фильма, созданную пользователем.

      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
            format: Bearer jwt

      requestBody:
        description: Полный набор информации и идентификатор редактируемого фильма.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateFilm'
        required: true

      responses:
        "200":
          description: Фильм обновлен. Новый объект фильма.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/film'

        "400":
          description: Неверный формат запроса.

        "401":
          description: Пользователь не авторизован. 

        "403":
          description: Редактировать фильм может только владелец.

        "404":
          description: Фильма с заданным идентификатором не существует.

    delete:
      tags:
        - films
      summary: Удаление карточки фильма
      description: Удаляет карточку фильма, созданную пользователем

      parameters:
        - in: path
          name: filmId
          schema:
            type: string
            format: uuid
          required: true
          description: Идентификатор фильма
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
            format: Bearer jwt

      requestBody:
        description: Идентификатор пользователя, пытающегося удалить фильм.
        content:
          application/json:
            schema:
              type: object

      responses:
        "204":
          description: Фильм успешно удален.

        "401":
          description: Пользователь не авторизован.

        "403":
          description: Удалять фильм может только создатель.

        "404":
          description: Фильма с зфданным идентификатором не существует.

  /films?limit=60&genre=comedy:
    get:
      tags:
        - films
      summary: Получение списка фильмов
      description: Возвращает список фильмов (по умолчанию не больше 60).

      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            default: 60
            example: 10

        - in: query
          name: genre
          schema:
            type: string
            enum: [ 
              comedy, 
              crime,
              documentary, 
              drama, 
              horror, 
              family, 
              romance, 
              scifi, 
              thriller ]
            example: comedy

      responses:
        "200":
          description: Успешно. Список фильмов.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/filmSearchResponse'

        "400":
          description: Неверный формат запроса.


  /films/promo:
    get:
      tags:
        - films
      summary: Получение промо-фильма
      description: Получение детальной информации по промо фильму.

      responses:
        "200":
          description: Успешно. Детальная информация по промо фильму.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/film'


  /films/watch:
    get:
      tags:
        - films
      summary: Получить список фильмов «К просмотру»
      description: Возвращает список фильмов, добавленных к просмотру


      responses:
        "200":
          description: Успешно. Фильмы, добавленные к просмотру.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/film'

        "401":
          description: Пользователь не авторизован. Запрос отклонен.


    post:
      tags:
        - films
      summary: Добавить фильм в список "К просмотру"
      description: Добавляет фильм в список "К просмотру"

      requestBody:
        description: Id фильма, который добавляют в список.
        content:
          application/json:
            schema:
              type: object

              properties:
                filmId:
                  type: string
                  format: uuid
                  example: 6329c3d6a04ab1061c6425ease8u342

              required:
                - filmId

      responses:
        "201":
          description: Успешно. Фильм добавлен в список "К просмотру".

        "401":
          description: Пользователь не авторизован. Запрос отклонен.


    delete:
      tags:
        - films
      summary: Удалить фильм из списка "К просмотру"
      description: Удаляет фильм из списка "К просмотру"

      requestBody:
        description: Id этого фильма.
        content:
          application/json:
            schema:
              type: object

              properties:
                filmId:
                  type: string
                  format: uuid
                  example: 6329c3d6a04ab1061c6425ease8u342

              required:
                - filmId

      responses:
        "204":
          description: Успешно. Фильм удален из списка "К просмотру".

        "401":
          description: Пользователь не авторизован. Запрос отклонен.


  /films/{filmId}/comments:
    get:
      tags:
        - comments
      summary: Получить список комментариев для определённого фильма
      description: Возвращает список комментариев для определенного фильма.

      parameters:
        - in: path
          name: filmId
          schema:
            type: string
            format: uuid
          required: true
          description: Film id to get comments.

      responses:
        "200":
          description: Успешно. Список комментариев к фильму.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/comment'

        "404":
          description: Фильм с таким id не существует.


  /comments:
    post:
      tags:
        - comments
      summary: Добавить новый комментарий к определённому фильму
      description: Добавляет новый комментарий к определенному фильму.

      requestBody:
        description: Id фильма, к которому добавляют комментарий, и сам комментарий.
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/comment'
                - type: object
                  properties:
                    filmId:
                      type: string
                      format: uuid
                      example: 6329c3d6a04ab1061c6425ea
                  required:
                    - filmId

      responses:
        "200":
          description: Успешно. Комментарий добавлен.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comment'

        "400":
          description: Неверный формат запроса.

        "401":
          description: Пользователь не авторизован. Запрос отклонен.

        "404":
          description: Фильм с данным id не найден.


components:
  schemas:
    createUser:
      type: object

      properties:
        email:
          type: string
          format: email
          example: test@mail.ru

        name:
          type: string
          minLength: 1
          maxLength: 15
          example: test

        password:
          type: string
          minLength: 6
          maxLength: 12
          example: 123456

        avatar:
          type: string
          format: binary

          required:
            - email
            - password
            - name

    user:
      type: object

      properties:
        id:
          type: string
          format: uuid
          example: 6329c3d6a04ab1061c6425ea

        email:
          type: string
          example: test@mail.ru

        avatar:
          type: string
          format: uri
          pattern: ([^\s]+(\.(jpg|png))$)
          example: /upload/avatar.png

    CreateFilmDto:
      type: object

      properties:
        title:
          type: string
          minLength: 2
          maxLength: 100
          example: Один дома 10

        description:
          type: string
          minLength: 20
          maxLength: 1024
          example: Малой охраняет дом

        publicationDate:
          type: string
          format: date-time
          example: 2022-10-21T22:55:33.903Z

        genre:
          type: string
          enum: [ comedy, crime, documentary, drama, horror, family, romance, scifi, thriller ]
          example: comedy

        releaseYear:
          type: integer
          minimum: 1895
          maximum: 2022
          example: 2013

        previewLink:
          type: string
          format: url
          example: https://www.what-to-watch.ru/preview

        link:
          type: string
          format: url
          example: https://www.what-to-watch.ru/film

        actors:
          type: array
          items:
            type: string
          minItems: 1
          uniqueItems: true
          example: [ Дженнифер Лоуренс, Джош Хатчерсон, Лиам Хемсворт ]

        producer:
          type: string
          minLength: 2
          maxLength: 50
          example: Гэри Росс

        durationInMinutes:
          type: number
          minimum: 0.1

        posterLink:
          type: string
          format: uri
          pattern: ([^\s]+(\.jpg)$)
          example: film_poster.jpg

        backgroundImageLink:
          type: string
          format: uri
          pattern: ([^\s]+(\.jpg)$)
          example: film_bg.jpg

        backgroundColor:
          type: string
          example: green

      required:
        - title
        - description
        - publicationDate
        - genre
        - releaseYear
        - previewLink
        - link
        - actors
        - director
        - durationInMinutes
        - posterLink
        - backgroundImageLink
        - backgroundColor

    film:
      type: object

      properties:
        title:
          type: string
          minLength: 2
          maxLength: 100
          example: Один дома 10

        description:
          type: string
          minLength: 20
          maxLength: 1024
          example: Малой охраняет дом

        publicationDate:
          type: string
          format: date-time
          example: 2022-10-21T22:55:33.903Z

        genre:
          type: string
          enum: [ comedy, crime, documentary, drama, horror, family, romance, scifi, thriller ]
          example: comedy

        releaseYear:
          type: integer
          minimum: 1895
          maximum: 2022
          example: 2010

        rating:
          type: integer
          minimum: 0
          maximum: 10
          example: 1

        previewLink:
          type: string
          format: url
          example: https://www.what-to-watch.ru/preview

        link:
          type: string
          format: url
          example: https://www.what-to-watch.ru/url

        actors:
          type: array
          items:
            type: string
          minItems: 1
          uniqueItems: true
          example: [ Дженнифер Лоуренс, Джош Хатчерсон, Лиам Хемсворт ]

        producer:
          type: string
          minLength: 2
          maxLength: 50
          example: Трокс

        durationInMinutes:
          type: number
          minimum: 0.1
          example: 60

        commentsCount:
          type: integer
          minimum: 0
          example: 10

        user:
          $ref: '#/components/schemas/user'

        posterLink:
          type: string
          format: uri
          pattern: ([^\s]+(\.jpg)$)
          example: film_poster.jpg

        backgroundImageLink:
          type: string
          format: uri
          pattern: ([^\s]+(\.jpg)$)
          example: film_bg.jpg

        backgroundColor:
          type: string
          example: green

      required:
        - title
        - description
        - publicationDate
        - genre
        - releaseYear
        - rating
        - previewLink
        - link
        - actors
        - producer
        - durationInMinutes
        - commentsCount
        - user
        - posterLink
        - backgroundImageLink
        - backgroundColor

    updateFilm:
      allOf:
        - $ref: '#/components/schemas/film'
        - type: object
          properties:
            filmId:
              type: string
              format: uuid
              example: 6329c3d6a04ab1061c6425ea
          required:
            - filmId


    filmSearchResponse:
      type: object

      properties:
        title:
          type: string
          minLength: 2
          maxLength: 100
          example: Головоломка

        publicationDate:
          type: string
          format: date-time
          example: 2022-10-21T22:55:33.903Z

        genre:
          type: string
          enum: [ crime, comedy,  documentary, drama, horror, family, scifi, romance, thriller ]
          example: comedy

        previewLink:
          type: string
          format: url
          example: https://www.what-to-watch.ru/preview

        user:
          $ref: '#/components/schemas/user'

        posterLink:
          type: string
          format: uri
          pattern: ([^\s]+(\.jpg)$)
          example: poster.jpg

        commentsCount:
          type: integer
          minimum: 0
          example: 1

      required:
        - title
        - publicationDate
        - genre
        - previewLink
        - user
        - posterLink
        - commentsCount


    comment:
      type: object

      properties:
        text:
          type: string
          minLength: 5
          maxLength: 1024
          example: Круто!

        rating:
          type: integer
          minimum: 0
          maximum: 10
          example: 1


      required:
        - text
        - rating